const userData = {
  person: {
    professionalHeadline: 'Full-Stack Javascript Developer',
    completion: 1,
    showPhone: false,
    created: '2021-05-16T16:30:41Z',
    verified: true,
    flags: {
      benefits: true,
      canary: false,
      enlauSource: false,
      fake: false,
      featureDiscovery: true,
      firstSignalSent: true,
      signalsOnboardingCompleted: true,
      importingLinkedin: true,
      onBoarded: true,
      remoter: true,
      signalsFeatureDiscovery: true,
      importingLinkedinRecommendations: true,
      contactsImported: true,
      appContactsImported: false,
      genomeCompletionAcknowledged: true,
      cvImported: true,
      communityCreatedPrivate: false,
      communityCreatedClaimed: false,
      connectBenefitsViewed: true,
    },
    weight: 390.6764,
    ggId: '1103719',
    completionStage: {
      stage: 3,
      progress: 1,
    },
    locale: 'en',
    subjectId: 1103719,
    picture:
      'https://res.cloudinary.com/torre-technologies-co/image/upload/v0/origin/starrgate/users/profile_8ea8fac18ab43a6e074510668621e7e575b8bcac.jpg',
    hasEmail: true,
    isTest: false,
    name: 'Mahdi Abubakar',
    links: [
      {
        id: 'nM4GDLGN',
        name: '',
        address: 'https://mahdiabubakar.me',
      },
      {
        id: 'Oj6K3aDy',
        name: 'linkedin',
        address: 'https://www.linkedin.com/in/mahdiabubakar/',
      },
      {
        id: 'BMLB15ry',
        name: 'twitter',
        address: 'https://twitter.com/NigerianCoder',
      },
    ],
    location: {
      name: 'Abuja, Federal Capital Territory, Nigeria',
      shortName: 'Abuja, Federal Capital Territory, Nigeria',
      country: 'Nigeria',
      latitude: 9.0764785,
      longitude: 7.398574,
      timezone: 'Africa/Lagos',
      timezoneOffSet: 3600000,
      placeId: 'ChIJ2S_WTF90ThARK6EOorQXvVM',
    },
    theme: 'blue500',
    id: '7M293e4N',
    pictureThumbnail:
      'https://res.cloudinary.com/torre-technologies-co/image/upload/c_fill,h_150,w_150/v0/origin/starrgate/users/profile_8ea8fac18ab43a6e074510668621e7e575b8bcac.jpg',
    claimant: false,
    summaryOfBio:
      'I like to receive and deal with challenging tasks. I am a very enthusiastic student and I like coding.',
    weightGraph:
      'https://hcti.io/v1/image/67ca7347-78ab-4015-b8bf-0ba1a0828968',
    publicId: 'nigeriancoder',
  },
  stats: {
    education: 2,
    jobs: 2,
    strengths: 40,
  },
  strengths: [
    {
      id: 'N8JWq2Yj',
      code: 29411,
      name: 'Ruby on Rails',
      proficiency: 'no-experience-interested',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-12-28T17:06:13',
    },
    {
      id: 'yX719AYj',
      code: 7497,
      name: 'Testing',
      proficiency: 'proficient',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-12-28T17:06:10',
    },
    {
      id: 'yJeDQxkj',
      code: 28888,
      name: 'REST',
      proficiency: 'novice',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-12-28T17:06:07',
    },
    {
      id: 'MqAVE89M',
      code: 32021,
      name: 'Clojure',
      proficiency: 'novice',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-12-28T17:06:03',
    },
    {
      id: 'jp97wg9y',
      code: 49214,
      name: 'PostgreSQL',
      proficiency: 'novice',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-12-28T17:05:58',
    },
    {
      id: 'Nm638BbM',
      code: 63169,
      name: 'ReactJS',
      proficiency: 'master',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-11-06T00:01:35',
    },
    {
      id: 'jp9ADEvy',
      code: 59906,
      name: 'User-centered design',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-11-05T23:45:28',
    },
    {
      id: 'Nm638gqM',
      code: 68164,
      name: 'Mobile development',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-11-05T23:45:17',
    },
    {
      id: 'NaBXWGWM',
      code: 32059,
      name: 'Scala',
      proficiency: 'novice',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-26T00:01:43',
    },
    {
      id: 'j6dqJzxN',
      code: 56482,
      name: 'Strategic Thinking',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-26T00:01:37',
    },
    {
      id: 'MqAkYbbM',
      code: 50182,
      name: 'React',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-14T07:23:12',
    },
    {
      id: 'yZmBpDBj',
      code: 196338,
      name: 'Full Stack',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-13T14:31:39',
    },
    {
      id: 'yYoBo1KM',
      code: 6124164,
      name: 'Full Stack development',
      proficiency: 'no-experience-interested',
      additionalInfo: '',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-12T21:08:10',
    },
    {
      id: 'y0zAzKYM',
      code: 55521,
      name: 'Front-end development',
      proficiency: 'no-experience-interested',
      additionalInfo: '',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-12T21:08:10',
    },
    {
      id: 'NxzlzOgj',
      code: 61332,
      name: 'Software development',
      proficiency: 'no-experience-interested',
      additionalInfo: '',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-12T21:08:10',
    },
    {
      id: 'M4nWnZxy',
      code: 194792,
      name: 'Material design',
      proficiency: 'no-experience-interested',
      additionalInfo: '',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-12T21:08:10',
    },
    {
      id: 'ydzZP40M',
      code: 65332,
      name: 'Cloud',
      proficiency: 'proficient',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-13T14:31:29',
    },
    {
      id: 'ynrbQoPy',
      code: 44929,
      name: 'Java SE',
      proficiency: 'no-experience-interested',
      additionalInfo: '',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-12T21:08:10',
    },
    {
      id: 'xyXpkEky',
      code: 5993,
      name: 'AWS',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-09T23:13:52',
    },
    {
      id: 'LMgKx8gM',
      code: 21290,
      name: 'MongoDB',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-09T23:13:50',
    },
    {
      id: 'pyJlL9WM',
      code: 55630,
      name: 'TDD',
      proficiency: 'proficient',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-09T23:13:48',
    },
    {
      id: 'XMqa5mJM',
      code: 29351,
      name: 'EXPRESS',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-09T23:13:44',
    },
    {
      id: 'mjlQeXay',
      code: 6380,
      name: 'API',
      proficiency: 'master',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-09T02:05:40',
    },
    {
      id: 'ZNOlgBrM',
      code: 59162,
      name: 'SQL',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-09T02:05:38',
    },
    {
      id: 'xM9lwAWN',
      code: 1339751,
      name: 'Data base',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-09T02:05:36',
    },
    {
      id: '9MBlrWay',
      code: 17226,
      name: 'WordPress',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-09T02:05:30',
    },
    {
      id: 'pyoLE2PN',
      code: 23826,
      name: 'Vue.js',
      proficiency: 'proficient',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-06T15:03:48',
    },
    {
      id: 'Ajrrw2ej',
      code: 23813,
      name: 'Node.js',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-06T15:03:40',
    },
    {
      id: '8jp81gzj',
      code: 59925,
      name: 'Node',
      proficiency: 'proficient',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-10-01T22:49:15',
    },
    {
      id: '9ME3nJ1y',
      code: 18317,
      name: 'CSS3',
      proficiency: 'master',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-09-29T05:49:31',
    },
    {
      id: 'Vjw06wYy',
      code: 18318,
      name: 'HTML5',
      proficiency: 'master',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-09-29T05:49:07',
    },
    {
      id: 'wM7X02Dj',
      code: 32056,
      name: 'Python',
      proficiency: 'novice',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-09-15T03:18:28',
    },
    {
      id: '8jppEvmj',
      code: 603224,
      name: 'JavasScript',
      proficiency: 'master',
      weight: 0,
      recommendations: 1,
      media: [],
      supra: false,
      created: '2021-09-12T14:02:14',
    },
    {
      id: 'kNmpx9by',
      code: 42295,
      name: 'Express.js',
      proficiency: 'proficient',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-09-03T00:32:59',
    },
    {
      id: 'JMe289pj',
      code: 785265,
      name: 'React native',
      proficiency: 'proficient',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-09-03T00:33:06',
    },
    {
      id: 'nM4qnO5j',
      code: 32590,
      name: 'TypeScript',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-09-11T21:08:25',
    },
    {
      id: 'EM3Bm0bN',
      code: 23818,
      name: 'React.js',
      proficiency: 'expert',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-09-03T00:32:52',
    },
    {
      id: '5ykeYLPM',
      code: 18319,
      name: 'Javascript',
      proficiency: 'expert',
      weight: 0,
      recommendations: 1,
      media: [],
      supra: false,
      created: '2021-09-03T00:32:43',
    },
    {
      id: 'vN8ZXoej',
      code: 23009,
      name: 'CSS',
      proficiency: 'master',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-09-10T18:54:13',
    },
    {
      id: 'gyYep76y',
      code: 23802,
      name: 'HTML',
      proficiency: 'master',
      weight: 0,
      recommendations: 0,
      media: [],
      supra: false,
      created: '2021-09-10T18:54:23',
    },
  ],
  interests: [],
  experiences: [
    {
      id: 'EM354awy',
      category: 'education',
      name: "Bachelor's degree Computer Science",
      organizations: [
        {
          id: 746062,
          name: 'University of the People',
          publicId: 'UniversityOfThePeople',
          picture:
            'https://res.cloudinary.com/torre-technologies-co/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1626741927/origin/bio/organizations/noxygup88llziu3qi1h0.png',
        },
      ],
      responsibilities: [],
      fromYear: '2020',
      toYear: '2024',
      highlighted: true,
      weight: 0,
      verifications: 1,
      recommendations: 1,
      media: [],
      rank: 1,
      strengths: [],
    },
    {
      id: 'pyd1KvDN',
      category: 'jobs',
      name: 'Full-Stack Developer',
      organizations: [
        {
          id: 921618,
          name: 'L Johnson Fashion',
          publicId: 'LJohnsonFashion',
        },
      ],
      responsibilities: [],
      fromMonth: 'July',
      fromYear: '2021',
      remote: false,
      additionalInfo: '',
      highlighted: true,
      weight: 0,
      verifications: 1,
      recommendations: 1,
      media: [],
      rank: 1,
      strengths: [],
    },
    {
      id: '5yklKP8N',
      category: 'jobs',
      name: 'Chief Executive Officer',
      organizations: [
        {
          id: 921316,
          name: 'The Mahdisoft Inc',
          publicId: 'TheMahdisoftInc',
        },
      ],
      responsibilities: [],
      fromMonth: 'December',
      fromYear: '2018',
      additionalInfo: '',
      highlighted: true,
      weight: 0,
      verifications: 1,
      recommendations: 1,
      media: [],
      rank: 2,
      strengths: [],
    },
    {
      id: 'kNmab8EN',
      category: 'education',
      name: "Bachelor's degree Cyber Security",
      organizations: [
        {
          id: 650087,
          name: 'Federal University Dutse',
          publicId: 'FederalUniversityDutse',
          picture:
            'https://res.cloudinary.com/torre-technologies-co/image/upload/v1613414326/origin/bio/organizations/ozne5adovng5bcw2bmvv.png',
        },
      ],
      responsibilities: [],
      fromMonth: 'July',
      fromYear: '2021',
      remote: false,
      additionalInfo: '',
      highlighted: true,
      weight: 0,
      verifications: 0,
      recommendations: 0,
      media: [],
      rank: 2,
      strengths: [],
    },
  ],
  awards: [],
  jobs: [
    {
      id: 'pyd1KvDN',
      category: 'jobs',
      name: 'Full-Stack Developer',
      organizations: [
        {
          id: 921618,
          name: 'L Johnson Fashion',
          publicId: 'LJohnsonFashion',
        },
      ],
      responsibilities: [],
      fromMonth: 'July',
      fromYear: '2021',
      remote: false,
      additionalInfo: '',
      highlighted: true,
      weight: 0,
      verifications: 1,
      recommendations: 1,
      media: [],
      rank: 1,
      strengths: [],
    },
    {
      id: '5yklKP8N',
      category: 'jobs',
      name: 'Chief Executive Officer',
      organizations: [
        {
          id: 921316,
          name: 'The Mahdisoft Inc',
          publicId: 'TheMahdisoftInc',
        },
      ],
      responsibilities: [],
      fromMonth: 'December',
      fromYear: '2018',
      additionalInfo: '',
      highlighted: true,
      weight: 0,
      verifications: 1,
      recommendations: 1,
      media: [],
      rank: 2,
      strengths: [],
    },
  ],
  projects: [],
  publications: [],
  education: [
    {
      id: 'EM354awy',
      category: 'education',
      name: "Bachelor's degree Computer Science",
      organizations: [
        {
          id: 746062,
          name: 'University of the People',
          publicId: 'UniversityOfThePeople',
          picture:
            'https://res.cloudinary.com/torre-technologies-co/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1626741927/origin/bio/organizations/noxygup88llziu3qi1h0.png',
        },
      ],
      responsibilities: [],
      fromYear: '2020',
      toYear: '2024',
      highlighted: true,
      weight: 0,
      verifications: 1,
      recommendations: 1,
      media: [],
      rank: 1,
      strengths: [],
    },
    {
      id: 'kNmab8EN',
      category: 'education',
      name: "Bachelor's degree Cyber Security",
      organizations: [
        {
          id: 650087,
          name: 'Federal University Dutse',
          publicId: 'FederalUniversityDutse',
          picture:
            'https://res.cloudinary.com/torre-technologies-co/image/upload/v1613414326/origin/bio/organizations/ozne5adovng5bcw2bmvv.png',
        },
      ],
      responsibilities: [],
      fromMonth: 'July',
      fromYear: '2021',
      remote: false,
      additionalInfo: '',
      highlighted: true,
      weight: 0,
      verifications: 0,
      recommendations: 0,
      media: [],
      rank: 2,
      strengths: [],
    },
  ],
  opportunities: [
    {
      id: 'y0lP5lqy',
      interest: 'mentoring',
      field: 'active',
      data: false,
    },
    {
      id: 'M37913BM',
      interest: 'industries',
      field: 'types',
      data: [
        {
          code: 33345,
          locale: 'en',
          name: 'Web development',
        },
        {
          code: 33335,
          locale: 'en',
          name: 'Software development',
        },
        {
          locale: 'en',
          name: 'Front-end development',
        },
      ],
    },
    {
      id: 'yk63lR8j',
      interest: 'jobs-full-time',
      field: 'private',
      data: false,
    },
    {
      id: 'yZ7XkR9N',
      interest: 'jobs-full-time',
      field: 'private',
      data: false,
    },
    {
      id: 'Mq9qWRvM',
      interest: 'gigs',
      field: 'private',
      data: false,
    },
    {
      id: 'yJ8aoEEM',
      interest: 'gigs',
      field: 'private',
      data: false,
    },
    {
      id: 'Mgl7akmj',
      interest: 'internships',
      field: 'active',
      data: true,
    },
    {
      id: 'yX3JvRpj',
      interest: 'internships',
      field: 'active',
      data: true,
    },
    {
      id: 'N8GK5p7y',
      interest: 'internships',
      field: 'private',
      data: false,
    },
    {
      id: 'yzl6AqQM',
      interest: 'internships',
      field: 'private',
      data: false,
    },
    {
      id: 'NKzKo1Dy',
      interest: 'gigs',
      field: 'active',
      data: true,
    },
    {
      id: 'yZ7blG0N',
      interest: 'jobs-full-time',
      field: 'active',
      data: true,
    },
    {
      id: 'MBZvBXkM',
      interest: 'hiring',
      field: 'active',
      data: true,
    },
    {
      id: 'MvnVDa3M',
      interest: 'internships',
      field: 'desirable-compensation-currency',
      data: 'USD$',
    },
    {
      id: 'Mq9bgkJM',
      interest: 'internships',
      field: 'desirable-compensation-periodicity',
      data: 'hourly',
    },
    {
      id: 'yJ8bBPWM',
      interest: 'internships',
      field: 'desirable-compensation-amount',
      data: 10,
    },
    {
      id: 'MglwLegj',
      interest: 'internships',
      field: 'desirable-compensation-publicly-visible',
      data: true,
    },
    {
      id: 'yX3qWBkj',
      interest: 'jobs',
      field: 'desirable-compensation-currency',
      data: 'USD$',
    },
    {
      id: 'N8GDBzDy',
      interest: 'jobs',
      field: 'desirable-compensation-periodicity',
      data: 'hourly',
    },
    {
      id: 'yZ7gPB0N',
      interest: 'jobs',
      field: 'desirable-compensation-amount',
      data: 10,
    },
    {
      id: 'M37gBqmM',
      interest: 'jobs',
      field: 'desirable-compensation-publicly-visible',
      data: true,
    },
    {
      id: 'NmgLplXj',
      interest: 'gigs',
      field: 'desirable-compensation-currency',
      data: 'USD$',
    },
    {
      id: 'Me6K23aj',
      interest: 'gigs',
      field: 'desirable-compensation-periodicity',
      data: 'hourly',
    },
    {
      id: 'jAmEB0vj',
      interest: 'gigs',
      field: 'desirable-compensation-amount',
      data: 10,
    },
    {
      id: 'jpErJm9y',
      interest: 'gigs',
      field: 'desirable-compensation-publicly-visible',
      data: true,
    },
  ],
  languages: [
    {
      code: 'en',
      language: 'English',
      fluency: 'fully-fluent',
    },
    {
      code: 'ha',
      language: 'Hausa',
      fluency: 'fully-fluent',
    },
  ],
  personalityTraitsResults: {
    groups: [
      {
        id: 'extraversion',
        order: 0,
        median: 3.5,
        stddev: 0.57,
      },
      {
        id: 'openness-to-experience',
        order: 1,
        median: 3.41,
        stddev: 0.6,
      },
      {
        id: 'conscientiousness',
        order: 2,
        median: 3.44,
        stddev: 0.56,
      },
      {
        id: 'agreeableness',
        order: 3,
        median: 2.94,
        stddev: 0.58,
      },
      {
        id: 'honesty-humility',
        order: 4,
        median: 3.19,
        stddev: 0.62,
      },
      {
        id: 'emotionality',
        order: 5,
        median: 3.43,
        stddev: 0.62,
      },
    ],
    analyses: [
      {
        groupId: 'openness-to-experience',
        analysis: 3.44,
      },
      {
        groupId: 'honesty-humility',
        analysis: 3.38,
      },
      {
        groupId: 'agreeableness',
        analysis: 3.25,
      },
      {
        groupId: 'altruism',
        analysis: 3.75,
      },
      {
        groupId: 'conscientiousness',
        analysis: 3.69,
      },
      {
        groupId: 'emotionality',
        analysis: 2.81,
      },
      {
        groupId: 'extraversion',
        analysis: 3,
      },
    ],
  },
  professionalCultureGenomeResults: {
    groups: [
      {
        id: '7',
        nativeOrder: 7,
        text: {
          common: 'Calm',
        },
        answer: '4',
        order: 0,
        median: 3.220002337,
        stddev: 0.7320363351,
      },
      {
        id: '8',
        nativeOrder: 8,
        text: {
          common: 'Careful',
        },
        answer: '4',
        order: 1,
        median: 3.297779509,
        stddev: 0.721817971,
      },
      {
        id: '19',
        nativeOrder: 19,
        text: {
          common: 'Quick to take advantage of opportunities',
        },
        answer: '4',
        order: 2,
        median: 3.155788266,
        stddev: 0.7910802406,
      },
      {
        id: '28',
        nativeOrder: 27,
        text: {
          common: 'Cooperative',
        },
        answer: '4',
        order: 3,
        median: 3.637398991,
        stddev: 0.5441371579,
      },
      {
        id: '2',
        nativeOrder: 2,
        text: {
          common: 'Action-oriented',
        },
        answer: '3',
        order: 4,
        median: 3.182707783,
        stddev: 0.7414651075,
      },
      {
        id: '3',
        nativeOrder: 3,
        text: {
          common: 'Adaptable',
        },
        answer: '3',
        order: 5,
        median: 3.53455274,
        stddev: 0.6204672813,
      },
      {
        id: '4',
        nativeOrder: 4,
        text: {
          common: 'Avoiding conflict',
        },
        answer: '3',
        order: 6,
        median: 3.184795276,
        stddev: 0.8784443312,
      },
      {
        id: '5',
        nativeOrder: 5,
        text: {
          common: 'Aggressive',
        },
        answer: '3',
        order: 7,
        median: 0.8133620243,
        stddev: 0.8965000891,
      },
      {
        id: '6',
        nativeOrder: 6,
        text: {
          common: 'Analytical',
        },
        answer: '3',
        order: 8,
        median: 3.390055005,
        stddev: 0.6916525511,
      },
      {
        id: '11',
        nativeOrder: 11,
        text: {
          common: 'Decisive',
        },
        answer: '3',
        order: 9,
        median: 3.280022884,
        stddev: 0.7333204925,
      },
      {
        id: '12',
        nativeOrder: 12,
        text: {
          common: 'Easygoing',
        },
        answer: '3',
        order: 10,
        median: 3.418765284,
        stddev: 0.7478766839,
      },
      {
        id: '13',
        nativeOrder: 13,
        text: {
          common: 'Fair',
        },
        answer: '3',
        order: 11,
        median: 3.61264673,
        stddev: 0.6273839106,
      },
      {
        id: '14',
        nativeOrder: 14,
        text: {
          common: 'Honest',
        },
        answer: '3',
        order: 12,
        median: 3.849761837,
        stddev: 0.3852109863,
      },
      {
        id: '15',
        nativeOrder: 15,
        text: {
          common: 'Innovative',
        },
        answer: '3',
        order: 13,
        median: 3.391966471,
        stddev: 0.7194864422,
      },
      {
        id: '17',
        nativeOrder: 17,
        text: {
          common: 'People-oriented',
        },
        answer: '3',
        order: 14,
        median: 3.323092158,
        stddev: 0.7719721827,
      },
      {
        id: '18',
        nativeOrder: 18,
        text: {
          common: 'Precise',
        },
        answer: '3',
        order: 15,
        median: 3.202731585,
        stddev: 0.7136453554,
      },
      {
        id: '21',
        nativeOrder: 21,
        text: {
          common: 'Results-oriented',
        },
        answer: '3',
        order: 16,
        median: 3.402746414,
        stddev: 0.6924228714,
      },
      {
        id: '23',
        nativeOrder: 51,
        text: {
          common: 'Supportive',
        },
        answer: '3',
        order: 17,
        median: 3.521348496,
        stddev: 0.6202686763,
      },
      {
        id: '24',
        nativeOrder: 23,
        text: {
          common: 'Team-oriented',
        },
        answer: '3',
        order: 18,
        median: 3.515253662,
        stddev: 0.6403773213,
      },
      {
        id: '26',
        nativeOrder: 25,
        text: {
          common: 'Willing to experiment',
        },
        answer: '3',
        order: 19,
        median: 3.336304234,
        stddev: 0.7469585025,
      },
      {
        id: '29',
        nativeOrder: 28,
        text: {
          common: 'Focused on professional growth',
        },
        answer: '3',
        order: 20,
        median: 3.640229705,
        stddev: 0.5835093756,
      },
      {
        id: '30',
        nativeOrder: 29,
        text: {
          common: 'Quality-driven',
        },
        answer: '3',
        order: 21,
        median: 3.622124519,
        stddev: 0.5685579656,
      },
      {
        id: '31',
        nativeOrder: 52,
        text: {
          common: 'Fast-moving',
        },
        answer: '3',
        order: 22,
        median: 3.078259813,
        stddev: 0.7687488044,
      },
      {
        id: '34',
        nativeOrder: 31,
        text: {
          common: 'Highly expectant for performance',
        },
        answer: '3',
        order: 23,
        median: 3.490903614,
        stddev: 0.6463617196,
      },
      {
        id: '38',
        nativeOrder: 35,
        text: {
          common: 'Able to learn from mistakes',
        },
        answer: '3',
        order: 24,
        median: 3.685785863,
        stddev: 0.5356724665,
      },
      {
        id: '39',
        nativeOrder: 36,
        text: {
          common: 'Listening to customers',
        },
        answer: '3',
        order: 25,
        median: 3.684881005,
        stddev: 0.5685013891,
      },
      {
        id: '42',
        nativeOrder: 38,
        text: {
          common: 'Detail-oriented',
        },
        answer: '3',
        order: 26,
        median: 3.530555446,
        stddev: 0.6241323568,
      },
      {
        id: '45',
        nativeOrder: 41,
        text: {
          common: 'Respectful',
        },
        answer: '3',
        order: 27,
        median: 3.862969241,
        stddev: 0.3800380304,
      },
      {
        id: '46',
        nativeOrder: 42,
        text: {
          common: 'Risk-taker',
        },
        answer: '3',
        order: 28,
        median: 2.843108659,
        stddev: 0.8711670703,
      },
      {
        id: '53',
        nativeOrder: 49,
        text: {
          common:
            'Oriented towards acquiring knowledge over acquiring connections',
        },
        answer: '3',
        order: 29,
        median: 2.07754721,
        stddev: 1.153373214,
      },
      {
        id: '54',
        nativeOrder: 50,
        text: {
          common: 'Team player',
        },
        answer: '3',
        order: 30,
        median: 3.504892548,
        stddev: 0.6398516423,
      },
      {
        id: '1',
        nativeOrder: 1,
        text: {
          common: 'Achievement-oriented',
        },
        answer: '2',
        order: 31,
        median: 3.307087211,
        stddev: 0.7408654995,
      },
      {
        id: '9',
        nativeOrder: 9,
        text: {
          common: 'Competitive',
        },
        answer: '2',
        order: 32,
        median: 2.983387237,
        stddev: 0.9488376744,
      },
      {
        id: '10',
        nativeOrder: 10,
        text: {
          common: 'Customer-oriented',
        },
        answer: '2',
        order: 33,
        median: 3.426673945,
        stddev: 0.7629528583,
      },
      {
        id: '16',
        nativeOrder: 16,
        text: {
          common: 'Market-driven',
        },
        answer: '2',
        order: 34,
        median: 2.704610857,
        stddev: 0.9381360182,
      },
      {
        id: '20',
        nativeOrder: 20,
        text: {
          common: 'Reflective',
        },
        answer: '2',
        order: 35,
        median: 3.200198307,
        stddev: 0.7582734099,
      },
      {
        id: '22',
        nativeOrder: 22,
        text: {
          common: 'Rule-oriented',
        },
        answer: '2',
        order: 36,
        median: 3.119940441,
        stddev: 0.8511788641,
      },
      {
        id: '25',
        nativeOrder: 24,
        text: {
          common: 'Tolerant',
        },
        answer: '2',
        order: 37,
        median: 3.429954405,
        stddev: 0.6756940264,
      },
      {
        id: '27',
        nativeOrder: 26,
        text: {
          common: 'Conflict-resolution-oriented',
        },
        answer: '2',
        order: 38,
        median: 3.101074538,
        stddev: 0.9032905675,
      },
      {
        id: '32',
        nativeOrder: 53,
        text: {
          common: 'Hard-driving',
        },
        answer: '2',
        order: 39,
        median: 2.843729747,
        stddev: 1.108178542,
      },
      {
        id: '33',
        nativeOrder: 30,
        text: {
          common: 'Highly ethical',
        },
        answer: '2',
        order: 40,
        median: 3.627091571,
        stddev: 0.6464404497,
      },
      {
        id: '35',
        nativeOrder: 32,
        text: {
          common: 'Integrity-driven',
        },
        answer: '2',
        order: 41,
        median: 3.754173109,
        stddev: 0.4849079849,
      },
      {
        id: '41',
        nativeOrder: 37,
        text: {
          common: 'Unhindered by many rules',
        },
        answer: '2',
        order: 42,
        median: 2.395910707,
        stddev: 1.044083104,
      },
      {
        id: '43',
        nativeOrder: 39,
        text: {
          common: 'Predictable',
        },
        answer: '2',
        order: 43,
        median: 2.931484545,
        stddev: 0.8854629428,
      },
      {
        id: '44',
        nativeOrder: 40,
        text: {
          common: "Focused towards organizational goals over unit's goals",
        },
        answer: '2',
        order: 44,
        median: 2.817963301,
        stddev: 0.9484849627,
      },
      {
        id: '47',
        nativeOrder: 43,
        text: {
          common: 'Driven by security of employment',
        },
        answer: '2',
        order: 45,
        median: 3.169801154,
        stddev: 0.8803406124,
      },
      {
        id: '48',
        nativeOrder: 44,
        text: {
          common: 'Open with information',
        },
        answer: '2',
        order: 46,
        median: 2.204781432,
        stddev: 1.247555541,
      },
      {
        id: '49',
        nativeOrder: 45,
        text: {
          common: 'Stable',
        },
        answer: '2',
        order: 47,
        median: 3.373058016,
        stddev: 0.7308361333,
      },
      {
        id: '50',
        nativeOrder: 46,
        text: {
          common: 'Ready to claim responsibility',
        },
        answer: '2',
        order: 48,
        median: 3.385036017,
        stddev: 0.729758287,
      },
      {
        id: '51',
        nativeOrder: 47,
        text: {
          common: 'Ready to take initiative',
        },
        answer: '2',
        order: 49,
        median: 3.303996319,
        stddev: 0.7403525539,
      },
      {
        id: '52',
        nativeOrder: 48,
        text: {
          common: 'Urgent',
        },
        answer: '2',
        order: 50,
        median: 2.606840978,
        stddev: 0.9817675335,
      },
      {
        id: '36',
        nativeOrder: 33,
        text: {
          common: 'Confrontational',
        },
        answer: '1',
        order: 51,
        median: 0.8046163721,
        stddev: 0.9958574145,
      },
      {
        id: '37',
        nativeOrder: 34,
        text: {
          common: 'Transparent with individual goals',
        },
        answer: '1',
        order: 52,
        median: 3.090594345,
        stddev: 0.9397403977,
      },
      {
        id: '40',
        nativeOrder: 54,
        text: {
          common: 'Oriented towards making their numbers',
        },
        answer: '1',
        order: 53,
        median: 3.194500771,
        stddev: 0.8527745846,
      },
    ],
    analyses: [
      {
        groupId: '7',
        analysis: 4,
      },
      {
        groupId: '8',
        analysis: 4,
      },
      {
        groupId: '19',
        analysis: 4,
      },
      {
        groupId: '28',
        analysis: 4,
      },
      {
        groupId: '2',
        analysis: 3,
      },
      {
        groupId: '3',
        analysis: 3,
      },
      {
        groupId: '4',
        analysis: 3,
      },
      {
        groupId: '5',
        analysis: 3,
      },
      {
        groupId: '6',
        analysis: 3,
      },
      {
        groupId: '11',
        analysis: 3,
      },
      {
        groupId: '12',
        analysis: 3,
      },
      {
        groupId: '13',
        analysis: 3,
      },
      {
        groupId: '14',
        analysis: 3,
      },
      {
        groupId: '15',
        analysis: 3,
      },
      {
        groupId: '17',
        analysis: 3,
      },
      {
        groupId: '18',
        analysis: 3,
      },
      {
        groupId: '21',
        analysis: 3,
      },
      {
        groupId: '23',
        analysis: 3,
      },
      {
        groupId: '24',
        analysis: 3,
      },
      {
        groupId: '26',
        analysis: 3,
      },
      {
        groupId: '29',
        analysis: 3,
      },
      {
        groupId: '30',
        analysis: 3,
      },
      {
        groupId: '31',
        analysis: 3,
      },
      {
        groupId: '34',
        analysis: 3,
      },
      {
        groupId: '38',
        analysis: 3,
      },
      {
        groupId: '39',
        analysis: 3,
      },
      {
        groupId: '42',
        analysis: 3,
      },
      {
        groupId: '45',
        analysis: 3,
      },
      {
        groupId: '46',
        analysis: 3,
      },
      {
        groupId: '53',
        analysis: 3,
      },
      {
        groupId: '54',
        analysis: 3,
      },
      {
        groupId: '1',
        analysis: 2,
      },
      {
        groupId: '9',
        analysis: 2,
      },
      {
        groupId: '10',
        analysis: 2,
      },
      {
        groupId: '16',
        analysis: 2,
      },
      {
        groupId: '20',
        analysis: 2,
      },
      {
        groupId: '22',
        analysis: 2,
      },
      {
        groupId: '25',
        analysis: 2,
      },
      {
        groupId: '27',
        analysis: 2,
      },
      {
        groupId: '32',
        analysis: 2,
      },
      {
        groupId: '33',
        analysis: 2,
      },
      {
        groupId: '35',
        analysis: 2,
      },
      {
        groupId: '41',
        analysis: 2,
      },
      {
        groupId: '43',
        analysis: 2,
      },
      {
        groupId: '44',
        analysis: 2,
      },
      {
        groupId: '47',
        analysis: 2,
      },
      {
        groupId: '48',
        analysis: 2,
      },
      {
        groupId: '49',
        analysis: 2,
      },
      {
        groupId: '50',
        analysis: 2,
      },
      {
        groupId: '51',
        analysis: 2,
      },
      {
        groupId: '52',
        analysis: 2,
      },
      {
        groupId: '36',
        analysis: 1,
      },
      {
        groupId: '37',
        analysis: 1,
      },
      {
        groupId: '40',
        analysis: 1,
      },
    ],
  },
};

export default userData;
